### ISSUE TITLE
documents, document_files関係のendpoint

### ISSUE THREAD

**Issue by iTakeshi** [hokui/hokui.net#110]
必要なエンドポイントの仕様を固めたいです

```
/api/documents
    GET /
    GET /exams
    GET /quizzes
    GET /summaries
    GET /personal_files
    GET /1
    PAT /1
    DEL /1

    GET /1/document_files

/api/document_files
    POS /                 # already_implemented
    GET /1
    GET /1/download_token # already implemented
    PAT /1
    DEL /1
```

こんなところかな？
他に必要なもの、または不要と思われるものなどコメントください

**Comment by endaaman** [comment]
`Document`の`exam`を取得するというのは、つまるところの`?min_code=0&max_code=999`のエイリアスであるようなものなので、`/api/documents?exams`というようなクエリーパラメーターの方が自然な気がします。`/api/documents/exams`というようなURLは取得時のフィルターにしかならないですし。
あとあくまでドキュメントという抽象的な資料に対するものなので、`personal_files`よりは`personal`の方がわかりやすいと思います。

**Comment by iTakeshi** [comment]
* `?type=exams`にしましょう。
* `personal`了解
* `exams`にanswerも含むようにするか、`?type=exams&include_answers=true`みたいなクエリ仕様にするか、どうしましょう

**Comment by endaaman** [comment]
別で取得するってこともあまりなさそうなのでexamだったら0から1999までで返しちゃって答えとはクライアントでよしなにって感じですかね

でもよく考えたらmax_code的なcodeに対する単純なフィルタだけにしておけばAPI側で意味づけすることもなくなって、実装的にもそこまで苦痛もないと思うので、それでもいいです

**Comment by iTakeshi** [comment]
`?code=0:1999`みたいなrange指定でどうだろう？

**Comment by iTakeshi** [comment]
`:`使うとparseに失敗するHTTP処理系があるらしいので、やるとしたら`?code=0-1999`かな

**Comment by endaaman** [comment]
ひと通り考えられそうなものを挙げてみます。

**code指定**
* `?min_code=0&max_code=1999` ... わかりやすいけどすごいださい
* `?code=0-1999` ... ちょっとクールだけど、この書き方は一般的なんですかね？

**API側で名前定義**

* `?type=exam` ... 安直
* `?exam` ... こういうのもなくないか

あれこれ言いましたけど、世の中によくある`検索`のためのクエリーパラメーターの概念と齟齬が起きなければ、あとは個人の美学に依るもんだと思うんで最終的にどうするかはおまかせします。

**Comment by iTakeshi** [comment]
どれも一長一短ぽいから一番見た目キレイな`?code=0-1999`でやってみます

**Comment by iTakeshi** [comment]
solved with #111, #114
