### ISSUE TITLE
ELMS新システムへの対応

### ISSUE THREAD

**Issue by endaaman** [hokui/hokui.net#113]
メールアドレスが2015年4月28日には強制的に`ec.hokudai.ac.jp`から`eis.hokudai.ac.jp`に変更になり、`ec.hokudai.ac.jp`は使えなくなるということで、バリデーション等修正だけでなく、現登録者のアドレスの変更などが必要になります。
デプロイやデータ移行の行程に少なからず影響が出そうなので、それについて対策を考えましょう。

**Comment by iTakeshi** [comment]
#### 新規会員登録
`eis`限定で登録可にすれば問題なし

#### データ移行
これが少し面倒だけど、考え方としては2つあります
1. そのままデータ移行して、`eis`への変更をうながす
2.  ユーザーを全消去して、全員新規登録にする

1の方法はマイルドだけど、データ移行作業中にパスワード変更（リセット）操作とかが重なりあったりすると不具合発生率が高くなると思う。特に、「メールアドレス変更をおねがいします」的なメールを流すと今までアクセスしていなかった人がパスワードリセット操作を実行する確率は高いのでほぼ間違いなくトラブる。
2はかなり乱暴だけどそこまで非現実的な案ではなくて、
* どのみちみんなメールアドレス変更の手続きをしてもらう必要がある
* 現存データで資料をアップロードしたことのある人がかなり少ない（< 50人）ため、ここの間を埋める移行スクリプトを書くほうが1の問題に対応するより簡単（タイミングをこちらで制御できるため）

**Comment by iTakeshi** [comment]
2案（一度User全消去）を採用しました
